AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bytewise SAM Template


Resources:

  BytwiseHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: default
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"

  BytewiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bytewise.handler
      CodeUri: resources/bytewise
      Runtime: python3.10
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Ref DependenciesLayer
      Events:
        BytewiseEvent:
          Type: HttpApi
          Properties:
            Path: /bytewise/{id}
            Method: GET
            ApiId: !Ref BytwiseHttpApi

  YoutubeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: resources/youtube
      Handler: youtube.handler
      Runtime: python3.10
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Ref DependenciesLayer
      Events:
        BytewiseEvent:
          Type: HttpApi
          Properties:
            Path: /youtube/{link}
            Method: POST 
            ApiId: !Ref BytwiseHttpApi
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject*
              Resource: !Sub "arn:aws:s3:::${youtube-bucket-${AWS::AccountId}}/*"
            - Effect: Allow
              Action:
                - S3:GetObject*
              Resource: !Sub "arn:aws:s3:::${youtube-bucket-${AWS::AccountId}}/*"


  GeneratePaySlipFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: resources/payslip
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 300
      Layers:
        - !Ref NodeJSCommonDependencies
        - !Ref PDFGeneratorNodeLayer
      Events:
        BytewiseEvent:
          Type: HttpApi
          Properties:
            Path: /payslip/generate
            Method: POST
            ApiId: !Ref BytwiseHttpApi
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject*
              Resource: !Sub "arn:aws:s3:::${PaySlipBucket}/*"
            - Effect: Allow
              Action:
                - S3:GetObject*
              Resource: !Sub "arn:aws:s3:::${PaySlipBucket}/*"
      Environment:
        Variables:
          payslip_bucket: !Ref PaySlipBucket
      

  YoutubeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "youtube-bucket-${AWS::AccountId}"

  BytewiseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bytewise-queue.fifo
      FifoQueue: true



  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/common
      CompatibleRuntimes:
        - python3.10
    Metadata:
      BuildMethod: python3.10

  PDFGeneratorNodeLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs18.x
      Content:
        S3Bucket: !Ref PDFLayerBucketRef
        S3Key: puppeteer.zip # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html
      Description: puppeteer
      LayerName: puppeteer
      LicenseInfo: MIT

  NodeJSDocumentsDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/nodeJsDocumentsDepenedenices
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
    DeletionPolicy: Retain


  NodeJSCommonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/nodeJsCommonDependencies
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
    DeletionPolicy: Retain



  PDFLayerBucketRef:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "horizon-hive-pdf-layer-bucket"

  PaySlipBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "horizon-hive-payslip-bucket"





