AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bytewise SAM Template


Resources:

  BytwiseHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: default
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"

  BytewiseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bytewise.handler
      CodeUri: resources/bytewise
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      Layers:
        - !Ref DependenciesLayer
      Events:
        BytewiseEvent:
          Type: HttpApi
          Properties:
            Path: /bytewise/{id}
            Method: GET
            ApiId: !Ref BytwiseHttpApi

  BytewiseQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bytewise-queue.fifo
      FifoQueue: true



  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/common
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7

  # PDFGeneratorNodeLayer:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     CompatibleRuntimes:
  #       - nodejs14.x
  #     Content:
  #       S3Bucket: !Ref PDFLayerBucketRef
  #       S3Key: puppeteer.zip # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html
  #     Description: puppeteer
  #     LayerName: puppeteer
  #     LicenseInfo: MIT

  NodeJSDocumentsDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/nodeJsDocumentsDepenedenices
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
    DeletionPolicy: Retain


  NodeJSCommonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/nodeJsCommonDependencies
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
    DeletionPolicy: Retain



  PDFLayerBucketRef:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "horizon-hive-pdf-layer-bucket"





